### ISSUE TITLE
error "DebugToolbarMiddleware is missing" on centos7

### ISSUE THREAD

**Issue by gitblessk** [allox/django-base-template-1.8#4]
I installed all the packages, and python34, and it failed, could you please help on it?

Thanks.
 
**wrapt-1.10.11
Install completed. Create Database
SystemCheckError: System check identified some issues:

ERRORS:
?: debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
        HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.**

**Comment by gitblessk** [comment]
i can see “debug_toolbar.middleware.DebugToolbarMiddleware” is already in base.py, but it just failed.

**Comment by gitblessk** [comment]
i remove debug_toolbar in install_apps, it works good, but without debug....

**Comment by Alex-CodeLab** [comment]
MIDDLEWARE_CLASSES renamed to MIDDLEWARE .
install script should work again for Django2/python3
